<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="myecore" nsURI="myURI" nsPrefix="myecore">
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1" eType="//User"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User"/>
  <eClassifiers xsi:type="ecore:EEnum" name="State">
    <eLiterals name="open" value="6"/>
    <eLiterals name="close" value="7"/>
  </eClassifiers>
</ecore:EPackage>
